### ISSUE TITLE
Incorrect restrict qualifiers on th_memmove

### ISSUE THREAD

**Issue by kjbracey** [eembc/audiomark#61]
`th_memmove` is used with overlapping source and destination, as you'd expect, but it has `restrict` qualifiers on its pointers, leading to undefined behaviour.

This prompts Arm Compiler 6 to use `__aeabi_memcpy` for the `memmove` inside the default implementation, rather than `__aeabi_memmove`.

**Comment by joseph-yiu** [comment]
Thanks for reporting the bug. This is now fixed.
